# Generated by Django 5.1.2 on 2024-10-12 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_mgt_app', '0002_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
