# Generated by Django 5.1.2 on 2024-10-12 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_mgt_app', '0004_remove_patient_name_patient_address_patient_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='hospital_id',
            new_name='clinic_id',
        ),
    ]
