# Generated by Django 5.1.2 on 2024-10-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_mgt_app', '0006_remove_patient_clinic_id_remove_patient_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='hospital_id',
            field=models.CharField(blank=True, editable=False, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
