# Generated by Django 5.1.2 on 2024-10-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_mgt_app', '0007_patient_hospital_id_alter_patient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='doctor_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='nurse_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
